[build]
  publish = "frontend/yieldzap-app/out"
  command = "cd frontend/yieldzap-app && npm install && npm run netlify-build"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
